version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api3
    # image: chiennn/chatbotapi:latest
    build:
       context: .
       dockerfile: dockerfile
    platform: linux/amd64
    restart: always
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      DB_USER: postgres
      DB_HOST: postgres
      DB_DATABASE: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: