

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

  api:
    container_name: api3
    #image: chiennn/gemini-api:latest
    platform: linux/amd64
    build:
      context: .  # 指向前端專案的根目錄
      dockerfile: dockerfile   
    restart: always
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

  chatbotfront:
    container_name: chatbotfront
    build:
      context: ../gemini-chatbot  # 指向前端專案的根目錄
      dockerfile: dockerfile    
    #image: chiennn/gemini-front:latest
    #platform: linux/amd64
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_URL: ${NEXT_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
    
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    

volumes:
  postgres_data:
  pgadmin_data: